CREATE TABLE SPRING_SESSION (
                                PRIMARY_ID CHAR(36) NOT NULL,
                                SESSION_ID CHAR(36) NOT NULL,
                                CREATION_TIME BIGINT NOT NULL,
                                LAST_ACCESS_TIME BIGINT NOT NULL,
                                MAX_INACTIVE_INTERVAL INT NOT NULL,
                                EXPIRY_TIME BIGINT NOT NULL,
                                PRINCIPAL_NAME VARCHAR(100),
                                CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)

);

CREATE UNIQUE INDEX SPRING_SESSION_INDEX ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_EXPIRY_IDX ON SPRING_SESSION (EXPIRY_TIME);

ALTER TABLE SPRING_SESSION
    ADD CONSTRAINT SPRING_SESSION_USERS_FK FOREIGN KEY (PRINCIPAL_NAME)
        REFERENCES users(username)
        ON DELETE SET NULL;